container_image = docker://jiakaiw/coupledquantumsystems:v5
universe = container

log = mcsolve_$(Cluster).log
error = mcsolve_$(Process).err
output = result_$(Process).zip

executable = qutip_run_python.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = $(Process).pkl, mcsolve_on_node.py

request_cpus = 4
request_memory = 4GB
request_disk = 2GB

queue 7000