container_image = docker://jiakaiw/coupledquantumsystems:v6
universe = container

log = qutip_opt_$(Cluster).log
error = qutip_opt_$(Process).err
output = result_$(Process).zip

executable = qutip_run_python.sh
arguments = $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = opt_ef_X.py, consolidated_optimization_results.json

request_cpus = 8
request_memory = 4GB
request_disk = 2GB

queue 870
